### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by deepx223** [Iswenzz/CGSC#1]
how to fix this
![image](https://user-images.githubusercontent.com/90983788/161823177-c6712637-a793-4ca2-be24-1f807520b6ad.png)

**Comment by Iswenzz** [comment]
Seems like it doesn't compile for the most recent CoD4x version, until i fix it you can remove the ``Scr_GetFunc`` line in ``cgsc_export.asm``.

**Comment by Iswenzz** [comment]
Fixed with [1.1.0](https://github.com/Iswenzz/CGSC/releases/tag/1.1.0)
