### ISSUE TITLE
Makefile additions

### ISSUE THREAD

**Issue by veteri** [Iswenzz/CGSC#2]
In your build instructions you mention some needed changes to the makefile of CoD4X.
How do these 3 lines make any sense?

```make
WIN_LLIBS:=$(WIN_LLIBS) CGSC
LINUX_LLIBS:=$(LINUX_LLIBS) CGSC
BSD_LLIBS:=$(BSD_LLIBS) CGSC
```
It's stating its requiring CGSC as a lib in order to be compiled, but we're trying to build it right now...
With this added the linker will complain he cant find CGSC, which makes sense.

`/usr/bin/ld: cannot find -lCGSC`

Looking forward to an explanation.

**Comment by veteri** [comment]
I figured it out. Your build instructions are written backwards.
For people who aren't very well versed with makefiles or the CoD4X build setup,
i'd recommend changing this:


> In order to use this extension, just download the archived file down below, and extract it to the cod4x server's src/CGSC directory, then copy the makefile snippet below and paste it before the default rule. Then simply build the cod4x source with make.

to something like this:

In order to use this extension, just download the archived file down below, and extract it to the cod4x server's src/CGSC directory, then copy the makefile snippet below and paste it before the default rule.
Then build the library itself by doing:
```
mkdir build && cd build
conan install .. --build missing --profile ../.conan/linux.conf
cmake ..
cmake --build .
```
Finally build the cod4x source with make.

**Comment by Iswenzz** [comment]
Ye the library itself is built with cmake Conan then the output lcgsc is
used in the makefile of the server. It also builds the asm files, I'll
update the Readme in a few days
